name: Run Tests

on:
  push:
    branches:
      - main # Kör tester vid push till main
  pull_request: # Kör tester vid pull requests
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run Component Tests
        run: npm run test:component

      - name: Run E2E Tests
        run: npm run test:e2e
